module.exports = {
    BOOKING_DURATION_IN_HOURS: 2,
    DEFAULT_BOOKING_CAPACITY: 2,
    DEFAULT_PORT: 3000,
    DEALERSHIP_WORKING_HOURS: {
        START_TIME: '09:00 AM',
        END_TIME: '05:00 PM',
    },
    HOUR_TO_MINUTE: 60,
};